// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// decode_bed_fast
NumericVector decode_bed_fast(RawVector raw_bytes, int n_samples);
RcppExport SEXP _PlinkArray_decode_bed_fast(SEXP raw_bytesSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type raw_bytes(raw_bytesSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(decode_bed_fast(raw_bytes, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// read_bed_subset
NumericMatrix read_bed_subset(std::string prefix, IntegerVector snp_indices, IntegerVector sample_indices, Nullable<int> n_total_samples);
RcppExport SEXP _PlinkArray_read_bed_subset(SEXP prefixSEXP, SEXP snp_indicesSEXP, SEXP sample_indicesSEXP, SEXP n_total_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type prefix(prefixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type snp_indices(snp_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sample_indices(sample_indicesSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type n_total_samples(n_total_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bed_subset(prefix, snp_indices, sample_indices, n_total_samples));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PlinkArray_decode_bed_fast", (DL_FUNC) &_PlinkArray_decode_bed_fast, 2},
    {"_PlinkArray_read_bed_subset", (DL_FUNC) &_PlinkArray_read_bed_subset, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PlinkArray(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
