# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decode_bed_fast <- function(raw_bytes, n_samples) {
    .Call(`_PlinkMatrix_decode_bed_fast`, raw_bytes, n_samples)
}

#' read subset for use in delayed matrix approach
#' @param prefix character path to bed resources and file prefix 
#' @param snp_indices integer vector of snp indices
#' @param sample_indices integer vector of sample indices
#' @param n_total_samples optional
#' @export
read_bed_subset <- function(prefix, snp_indices, sample_indices, n_total_samples = NULL) {
    .Call(`_PlinkMatrix_read_bed_subset`, prefix, snp_indices, sample_indices, n_total_samples)
}

read_bed_fast <- function(file_name, row_idx, col_idx, n_samples) {
    .Call(`_PlinkMatrix_read_bed_fast`, file_name, row_idx, col_idx, n_samples)
}

