# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decode_bed_fast <- function(raw_bytes, n_samples) {
    .Call(`_PlinkArray_decode_bed_fast`, raw_bytes, n_samples)
}

